### PR TITLE
fix long tweets from blue tick users, which have text mixed with its URL

### PR DESCRIPTION
**Pull request by j-fbriere**
This is to fix bug #711.

### CODE REVIEW

**Comment by TheHCJ** [comment]
I have merged this in my fritter fork called [Quacker](https://github.com/TheHCJ/Quacker/)

**Comment by jonjomckay** [comment]
Thanks!

**Comment by j-fbriere** [comment]
First you must be signed in to github.
Go the the [latest ci build](https://github.com/jonjomckay/fritter/actions/runs/4968226476) page, under artifacts click on the [apk-arm64](https://github.com/jonjomckay/fritter/suites/12876412183/artifacts/694607412) file link (most likely).
Download the file, then from the file explorer, under downloads, unzip the file and then install the file.

**Comment by nannadroid** [comment]
> First you must be signed in to github. Go the the [latest ci build](https://github.com/jonjomckay/fritter/actions/runs/4968226476) page, under artifacts click on the [apk-arm64](https://github.com/jonjomckay/fritter/suites/12876412183/artifacts/694607412) file link (most likely). Download the file, then from the file explorer, under downloads, unzip the file and then install the file.

Thanks for the answer! I first tried installing beta9 apk files from  [releases](https://github.com/jonjomckay/fritter/releases) page. But all of them say "App not installed". Screenshot is attached.
After your answer, I tried the apk from the link you provided. I still get same message. I use OnePlus6, Android 11.
Screenshot_20230524-005825__01
 What am I doing wrong?

**Comment by j-fbriere** [comment]
which file did you try to install, specifically?

**Pull request merged**
