### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by ManeraKai**
Here is the setup for translating the app's UI. Translation strings are in `/lib/lang/`. I've also extracted some strings and will extract more.

**Note:** This is just the setup. I published it as a PR to have some feedback.

### CODE REVIEW

**Comment by ManeraKai** [comment]
That extension ([i18n_extension](https://pub.dev/packages/i18n_extension)) has some nice features. The stock extension only has a getter function for strings. Nothing else. I'm positive about your suggestion 👍

**Comment by ManeraKai** [comment]
I'll start implementing it.

**Comment by jonjomckay** [comment]
Sounds good! One other thing that would be great is, would you mind changing the indentation back to how it currently is? It'd make it a lot easier to review. I can do a pass over with a formatter once it's merged in.

**Comment by ManeraKai** [comment]
> changing the indentation back to how it currently is
I'll try my best. btw what IDE do you use. Does it have a formatter? maybe it'll help me.

**Comment by jonjomckay** [comment]
@ManeraKai I haven't decided on a style yet, so I think it would be best to stick with the current formatting until then. Thanks!

**Comment by ManeraKai** [comment]
>It would be great to also add plural forms (probably only for votes count). Flutter supports zero, one, two, few, many and other.

Added that @Aga-C. I only found this was used in the trending page though.

**Comment by Aga-C** [comment]
@ManeraKai This should also have plural forms:
` "numberFormat_format_total_votes": "{numberFormatTotal} votes"`

**Comment by Aga-C** [comment]
Does it make sense to translate the name of the app?

**Comment by ManeraKai** [comment]
#116

**Review by jonjomckay — APPROVED** [review]

**Comment by jonjomckay** [comment]
@ManeraKai thanks a lot for this! Sorry it took so long to get merged.

I'll attempt to hook it up with Weblate ASAP.

**Pull request merged**
