### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Fritter/Fritter](https://hosted.weblate.org/projects/fritter/fritter/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Aga-C** [comment]
@jonjomckay I've seen on an emulator, that translations for tab names are gone (on home screen and in settings too):

image

**Comment by jonjomckay** [comment]
@Aga-C this should be fixed now in my latest commit. Thanks as always for picking this stuff up when I miss it!

**Comment by Aga-C** [comment]
@jonjomckay Can you unlock translating on Weblate?

**Comment by jonjomckay** [comment]
@Aga-C I've just unlocked it again. I'm not sure why it keeps getting locked...

**Pull request merged**
