### PR TITLE
[REQ] immediately return from status page

### PR DESCRIPTION
**Pull request by pohuing**
This is a hacky example of the behavior I'm proposing in #534

### CODE REVIEW

**Comment by pohuing** [comment]
I expect a proper implementation to take some toggle in the settings as well as maybe a more unified behavior when opening profiles etc. I think I can take care of that if this should become a proper feature.

**Comment by jonjomckay** [comment]
This should have already been fixed with aa54d3a19e27b010593b4798354382340f5a67ca. Can you confirm that it still isn't working with that fix in place?

**Comment by pohuing** [comment]
No, building straight from master does not show the home screen. This PR and issue is redundant then.
I had tested on the latest beta and stable release when I decided to fix this. Didn't expect this to work correctly on master, but that's a nice surprise!

**Comment by pohuing** [comment]
Since this is already done I'll just close this. Thanks for your quick reply!

**Comment by jonjomckay** [comment]
Great, no worries. Thanks for the PR anyway!

**Pull request closed without merging**
